/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountJsonldContextOneOf
 */
export interface AccountJsonldContextOneOf {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof AccountJsonldContextOneOf
     */
    '@vocab': string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonldContextOneOf
     */
    'hydra': AccountJsonldContextOneOfHydraEnum;
}

export const AccountJsonldContextOneOfHydraEnum = {
    http___www_w3_org_ns_hydra_core: 'http://www.w3.org/ns/hydra/core#'
} as const;

export type AccountJsonldContextOneOfHydraEnum = typeof AccountJsonldContextOneOfHydraEnum[keyof typeof AccountJsonldContextOneOfHydraEnum];


