/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'ipAddress': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Account
     */
    'roles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Account
     */
    'logs'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'userIdentifier'?: string;
}

