/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConstraintViolationJsonViolationsInner
 */
export interface ConstraintViolationJsonViolationsInner {
    /**
     * The property path of the violation
     * @type {string}
     * @memberof ConstraintViolationJsonViolationsInner
     */
    'propertyPath'?: string;
    /**
     * The message associated with the violation
     * @type {string}
     * @memberof ConstraintViolationJsonViolationsInner
     */
    'message'?: string;
}

