/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConstraintViolationJsonViolationsInner } from './constraint-violation-json-violations-inner';

/**
 * Unprocessable entity
 * @export
 * @interface ConstraintViolationJson
 */
export interface ConstraintViolationJson {
    /**
     * 
     * @type {number}
     * @memberof ConstraintViolationJson
     */
    'status'?: number;
    /**
     * 
     * @type {Array<ConstraintViolationJsonViolationsInner>}
     * @memberof ConstraintViolationJson
     */
    'violations'?: Array<ConstraintViolationJsonViolationsInner>;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJson
     */
    'detail'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJson
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJson
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolationJson
     */
    'instance'?: string | null;
}

