/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountJsonldContext } from './account-jsonld-context';

/**
 * A representation of common errors.
 * @export
 * @interface ErrorJsonld
 */
export interface ErrorJsonld {
    /**
     * 
     * @type {AccountJsonldContext}
     * @memberof ErrorJsonld
     */
    '@context'?: AccountJsonldContext;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    '@type'?: string;
    /**
     * A short, human-readable summary of the problem.
     * @type {string}
     * @memberof ErrorJsonld
     */
    'title'?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ErrorJsonld
     */
    'detail'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorJsonld
     */
    'status'?: number;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {string}
     * @memberof ErrorJsonld
     */
    'instance'?: string | null;
    /**
     * A URI reference that identifies the problem type
     * @type {string}
     * @memberof ErrorJsonld
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorJsonld
     */
    'description'?: string | null;
}

