/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommunicationExchangeInputJsonld } from '../models';
// @ts-ignore
import type { CommunicationExchangeOutputJsonld } from '../models';
// @ts-ignore
import type { ConstraintViolationJson } from '../models';
// @ts-ignore
import type { ConstraintViolationJsonldJsonld } from '../models';
// @ts-ignore
import type { ErrorJsonld } from '../models';
/**
 * CommunicationApi - axios parameter creator
 * @export
 */
export const CommunicationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a Communication resource.
         * @summary Creates a Communication resource.
         * @param {CommunicationExchangeInputJsonld} communicationExchangeInputJsonld The new Communication resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exchangePost: async (communicationExchangeInputJsonld: CommunicationExchangeInputJsonld, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'communicationExchangeInputJsonld' is not null or undefined
            assertParamExists('exchangePost', 'communicationExchangeInputJsonld', communicationExchangeInputJsonld)
            const localVarPath = `/api/exchange`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(communicationExchangeInputJsonld, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommunicationApi - functional programming interface
 * @export
 */
export const CommunicationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommunicationApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a Communication resource.
         * @summary Creates a Communication resource.
         * @param {CommunicationExchangeInputJsonld} communicationExchangeInputJsonld The new Communication resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exchangePost(communicationExchangeInputJsonld: CommunicationExchangeInputJsonld, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunicationExchangeOutputJsonld>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exchangePost(communicationExchangeInputJsonld, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunicationApi.exchangePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommunicationApi - factory interface
 * @export
 */
export const CommunicationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommunicationApiFp(configuration)
    return {
        /**
         * Creates a Communication resource.
         * @summary Creates a Communication resource.
         * @param {CommunicationApiExchangePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exchangePost(requestParameters: CommunicationApiExchangePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunicationExchangeOutputJsonld> {
            return localVarFp.exchangePost(requestParameters.communicationExchangeInputJsonld, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for exchangePost operation in CommunicationApi.
 * @export
 * @interface CommunicationApiExchangePostRequest
 */
export interface CommunicationApiExchangePostRequest {
    /**
     * The new Communication resource
     * @type {CommunicationExchangeInputJsonld}
     * @memberof CommunicationApiExchangePost
     */
    readonly communicationExchangeInputJsonld: CommunicationExchangeInputJsonld
}

/**
 * CommunicationApi - object-oriented interface
 * @export
 * @class CommunicationApi
 * @extends {BaseAPI}
 */
export class CommunicationApi extends BaseAPI {
    /**
     * Creates a Communication resource.
     * @summary Creates a Communication resource.
     * @param {CommunicationApiExchangePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommunicationApi
     */
    public exchangePost(requestParameters: CommunicationApiExchangePostRequest, options?: RawAxiosRequestConfig) {
        return CommunicationApiFp(this.configuration).exchangePost(requestParameters.communicationExchangeInputJsonld, options).then((request) => request(this.axios, this.basePath));
    }
}

