/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountJsonldContext } from './account-jsonld-context';

/**
 * 
 * @export
 * @interface AccountJsonld
 */
export interface AccountJsonld {
    /**
     * 
     * @type {AccountJsonldContext}
     * @memberof AccountJsonld
     */
    '@context'?: AccountJsonldContext;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    'ipAddress': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountJsonld
     */
    'roles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountJsonld
     */
    'logs'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AccountJsonld
     */
    'userIdentifier'?: string;
}

