/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountJsonldContext } from './account-jsonld-context';

/**
 * 
 * @export
 * @interface BookJsonld
 */
export interface BookJsonld {
    /**
     * 
     * @type {AccountJsonldContext}
     * @memberof BookJsonld
     */
    '@context'?: AccountJsonldContext;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof BookJsonld
     */
    'type': string;
    /**
     * 
     * @type {number}
     * @memberof BookJsonld
     */
    'stock': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BookJsonld
     */
    'rents'?: Array<string>;
}

