/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    'type': string;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    'stock': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Book
     */
    'rents'?: Array<string>;
}

