/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A representation of common errors.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * A short, human-readable summary of the problem.
     * @type {string}
     * @memberof ModelError
     */
    'title'?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ModelError
     */
    'detail'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'status'?: number;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {string}
     * @memberof ModelError
     */
    'instance'?: string | null;
    /**
     * A URI reference that identifies the problem type
     * @type {string}
     * @memberof ModelError
     */
    'type'?: string;
}

