/* tslint:disable */
/* eslint-disable */
/**
 * Hello API Platform
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountJsonldContext } from './account-jsonld-context';

/**
 * 
 * @export
 * @interface RentJsonld
 */
export interface RentJsonld {
    /**
     * 
     * @type {AccountJsonldContext}
     * @memberof RentJsonld
     */
    '@context'?: AccountJsonldContext;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    '@id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    '@type'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'rentDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'returnDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'returnExpectedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentJsonld
     */
    'book'?: string | null;
}

